name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          # Make tests import-safe & avoid real API calls in CI
          TESTING: "1"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'dummy' }}
          SECRET_KEY: "test-secret"
        run: python -m unittest discover -s tests -p "test_*.py"
